// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// native_open
SEXP native_open(std::string path, std::vector<std::string> columns, std::string encoding, double bytes);
RcppExport SEXP _AnotherSAS7bdat_native_open(SEXP pathSEXP, SEXP columnsSEXP, SEXP encodingSEXP, SEXP bytesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type columns(columnsSEXP);
    Rcpp::traits::input_parameter< std::string >::type encoding(encodingSEXP);
    Rcpp::traits::input_parameter< double >::type bytes(bytesSEXP);
    rcpp_result_gen = Rcpp::wrap(native_open(path, columns, encoding, bytes));
    return rcpp_result_gen;
END_RCPP
}
// native_next
SEXP native_next(SEXP ptr, int n);
RcppExport SEXP _AnotherSAS7bdat_native_next(SEXP ptrSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(native_next(ptr, n));
    return rcpp_result_gen;
END_RCPP
}
// native_close
void native_close(SEXP ptr);
RcppExport SEXP _AnotherSAS7bdat_native_close(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    native_close(ptr);
    return R_NilValue;
END_RCPP
}
// native_info
Rcpp::List native_info(SEXP ptr);
RcppExport SEXP _AnotherSAS7bdat_native_info(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(native_info(ptr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AnotherSAS7bdat_native_open", (DL_FUNC) &_AnotherSAS7bdat_native_open, 4},
    {"_AnotherSAS7bdat_native_next", (DL_FUNC) &_AnotherSAS7bdat_native_next, 2},
    {"_AnotherSAS7bdat_native_close", (DL_FUNC) &_AnotherSAS7bdat_native_close, 1},
    {"_AnotherSAS7bdat_native_info", (DL_FUNC) &_AnotherSAS7bdat_native_info, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_AnotherSAS7bdat(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
